DATA:
  DATA_SET: 'Fluo-N2DH-SIM+'
  USE_SILVER_TRUTH: False
  TRAIN_VAL_SPLIT: 0.1

TRAIN:
  CROP_SIZE: 512
  TRAIN_BATCH_SIZE: 8
  VAL_BATCH_SIZE: 8
  DISPLAY_IT: 200
  N_EPOCHS: 15
  TRAIN_SIZE: None
  VAL_SIZE: None
  DISPLAY: False