DATA:
  USE_SILVER_TRUTH: True
  DATA_SET: 'Fluo-N2DL-HeLa'
  TRAIN_VAL_SPLIT: 0.1

TRAIN:
  CROP_SIZE: 512
  TRAIN_BATCH_SIZE: 8
  VAL_BATCH_SIZE: 8
  DISPLAY_IT: 100  # 200
  N_EPOCHS: 15
  TRAIN_SIZE: None
  VAL_SIZE: None
  DISPLAY: True