DATA:
  USE_SILVER_TRUTH: True
  DATA_SET: 'Fluo-C2DL-MSC'
  TRAIN_VAL_SPLIT: 0.1

TRAIN:
  CROP_SIZE: 256
  TRAIN_BATCH_SIZE: 16
  VAL_BATCH_SIZE: 16
  DISPLAY_IT: 1000
  N_EPOCHS: 15
  TRAIN_SIZE: None
  VAL_SIZE: None
  DISPLAY: False